<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Kernels\basic_gemm_square.cl" />
    <None Remove="Kernels\gemm_bf16_layout5.cl" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Kernels\gemm_1_2048_2048_fused_layer_norm_shuffled.cl" />
    <EmbeddedResource Include="Kernels\gemm_1_2048_16n_fused_layer_norm.cl" />
    <EmbeddedResource Include="Kernels\gemm_1_2048_16n.cl" />
    <EmbeddedResource Include="Kernels\gemm_1_2048_16.cl" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Kernels\basic_gemm_square.cl" />
    <EmbeddedResource Include="Kernels\gemm_b_m_n.cl" />
    <EmbeddedResource Include="Kernels\gemm_8_2048_16.cl" />
    <EmbeddedResource Include="Kernels\gemm_8_32_16.cl" />
    <EmbeddedResource Include="Kernels\gemm_8_32_32.cl" />
    <EmbeddedResource Include="Kernels\gemm_8_16_16_col_maj.cl" />
    <EmbeddedResource Include="Kernels\gemm_8_16_16.cl" />
    <EmbeddedResource Include="Kernels\gemm_bf16_layout5.cl" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Foundation.OpenCL.Extensions.Intel\Foundation.OpenCL.Extensions.Intel.csproj" />
    <ProjectReference Include="..\..\src\Foundation.OpenCL\Foundation.OpenCL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
