<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Description>OpenCL binding for DotNet featuring idiomatic C# APIs with zero cost abstractions.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>OpenCL;GPGPU;HPC;C#;.NET;Bindings</PackageTags>
		<PackageProjectUrl>https://github.com/samuel-vidal/Foundation.OpenCL</PackageProjectUrl>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" />
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>